In [3]:
1
# 导入numpy并简写np
import numpy as np

In [4]:
2
#打印numpy的版本和配置
print(np.__version__)
np.show_config()

1.16.4
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/ubuntu/anaconda3/envs/tf/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/ubuntu/anaconda3/envs/tf/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/ubuntu/anaconda3/envs/tf/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/ubuntu/anaconda3/envs/tf/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/ubuntu/anaconda3/envs/tf/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/ubuntu/anaconda3/envs/tf/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/ubuntu/anaconda3/envs/tf/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/ubuntu/anaconda3/envs/tf/include']
lapack_opt_info:
    libraries = ['mkl_r

In [7]:
3 # 创建一个长度为10的空向量
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
4 # 如何找到任何一个数组的内存大小
Z=np.zeros((12, 12))
print("%d bytes" % (Z.size * Z.itemsize))

1152 bytes


In [12]:
5 # 如何从命令行得到numpy中add函数的说明文档？
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [13]:
6 # 创建一个长度为10并且除了第5个值为1的空向量
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [21]:
7 # 反转一个向量（第一个元素变为最后一个）
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [23]:
8 # 创建一个值域范围从10到49的向量
Z = np.arange(10, 50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [26]:
10 # 找到数组[1,2,0,0,4,0]中非0元素的位置索引
Z = [1,2,0,0,4,0]
nz = np.nonzero(Z)
print(nz)
# nz2 = Z[not 0]
# print (nz2)

(array([0, 1, 4]),)


In [27]:
11 # 创建一个3X3的单位矩阵
E = np.eye(3)
print(E)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
12 # 创建一个3X3X3的随机数组
R = np.random.random((3,3,3))
print (R)

[[[0.22736815 0.89698642 0.06623674]
  [0.73030679 0.24284949 0.24643997]
  [0.47756826 0.15378672 0.81496784]]

 [[0.60381159 0.06439626 0.16479989]
  [0.74248234 0.97677748 0.1472478 ]
  [0.495775   0.13972424 0.02902842]]

 [[0.24174846 0.67394643 0.37379132]
  [0.47158216 0.35682135 0.71684955]
  [0.71608699 0.76767795 0.97498275]]]


In [30]:
13 # 创建一个10X10的随机数组并找到他的最大值和最小值
Z = np.random.random((10, 10))
print(Z.min(), Z.max())

0.00198908080182314 0.9846814522413605


In [31]:
14 # 创建一个长度为30的随机变量并找到他的品均值
print(np.random.random(30).mean())

0.5139195333812422


In [35]:
15 # 创建一个二维数组，其中边界值为1，其余为0
z = np.ones((10, 10))
z[1:-1, 1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [37]:
16 # 对于一个存在数组，如何添加一个用0填充的边界？
z = np.ones((10,10))
z = np.pad(z, pad_width=1, mode='constant', constant_values=0)
print(z)


# pad(array, pad_width, mode, **kwargs)
# array——表示需要填充的数组；

# pad_width——表示每个轴（axis）边缘需要填充的数值数目。 
# 参数输入方式为：（(before_1, after_1), … (before_N, after_N)），其中(before_1, after_1)表示第1轴两边缘分别填充before_1个和after_1个数值。取值为：{sequence, array_like, int}

# mode——表示填充的方式（取值：str字符串或用户提供的函数）,总共有11种填充模式；


# constant’——表示连续填充相同的值，每个轴可以分别指定填充值，constant_values=（x, y）时前面用x填充，后面用y填充，缺省值填充0

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [38]:
17 # 以下表达式运行结果是什么？
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1


False

In [39]:
print (0 * np.nan)

nan


In [40]:
print(np.nan == np.nan)

False


In [41]:
print(np.inf > np.nan)

False


In [42]:
print(np.nan - np.nan)

nan


In [43]:
print(0.3 == 3 * 0.1)

False


In [45]:
18 # 创建一个5X5的矩阵，并设置值1， 2， 3， 4落在其对角线下方位置
z = np.diag(1 + np.arange(4), k=-1)
print(z)

# numpy.diag(v, k=0)[source]
# Extract a diagonal or construct a diagonal array.

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [46]:
19 # 创建一个8X8的矩阵，并且设置成棋盘样式
z = np.zeros((8, 8))
z[1::2, ::2] = 1
z[::2, 1::2] = 1
print(z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [52]:
20 # 考虑一个（6， 7， 8）形状的数组，其第100个元素的索引（x, y, z）是什么？
print(np.unravel_index(100, (6, 7, 8)))

(1, 5, 4)
