In [1]:
1
# 导入numpy并简写np
import numpy as np

In [2]:
2
#打印numpy的版本和配置
print(np.__version__)
np.show_config()

1.16.4
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/ubuntu/anaconda3/envs/tf/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/ubuntu/anaconda3/envs/tf/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/ubuntu/anaconda3/envs/tf/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/ubuntu/anaconda3/envs/tf/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/ubuntu/anaconda3/envs/tf/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/ubuntu/anaconda3/envs/tf/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/ubuntu/anaconda3/envs/tf/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/ubuntu/anaconda3/envs/tf/include']
lapack_opt_info:
    libraries = ['mkl_r

In [3]:
3 # 创建一个长度为10的空向量
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
4 # 如何找到任何一个数组的内存大小
Z=np.zeros((12, 12))
print("%d bytes" % (Z.size * Z.itemsize))

1152 bytes


In [5]:
5 # 如何从命令行得到numpy中add函数的说明文档？
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [6]:
6 # 创建一个长度为10并且除了第5个值为1的空向量
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
7 # 反转一个向量（第一个元素变为最后一个）
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [8]:
8 # 创建一个值域范围从10到49的向量
Z = np.arange(10, 50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
10 # 找到数组[1,2,0,0,4,0]中非0元素的位置索引
Z = [1,2,0,0,4,0]
nz = np.nonzero(Z)
print(nz)
# nz2 = Z[not 0]
# print (nz2)

(array([0, 1, 4]),)


In [10]:
11 # 创建一个3X3的单位矩阵
E = np.eye(3)
print(E)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
12 # 创建一个3X3X3的随机数组
R = np.random.random((3,3,3))
print (R)

[[[0.04049288 0.34322859 0.71997779]
  [0.06710502 0.68994669 0.57854874]
  [0.14296455 0.89040709 0.01061563]]

 [[0.78845729 0.10205374 0.13381858]
  [0.1309285  0.54494852 0.17814569]
  [0.5633222  0.27495194 0.84483249]]

 [[0.30789435 0.93880308 0.17738412]
  [0.90063232 0.08957394 0.78347877]
  [0.33594111 0.0692724  0.96359008]]]


In [12]:
13 # 创建一个10X10的随机数组并找到他的最大值和最小值
Z = np.random.random((10, 10))
print(Z.min(), Z.max())

0.0013912437754955986 0.986813466854602


In [13]:
14 # 创建一个长度为30的随机变量并找到他的品均值
print(np.random.random(30).mean())

0.5143445792755971


In [14]:
15 # 创建一个二维数组，其中边界值为1，其余为0
z = np.ones((10, 10))
z[1:-1, 1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [15]:
16 # 对于一个存在数组，如何添加一个用0填充的边界？
z = np.ones((10,10))
z = np.pad(z, pad_width=1, mode='constant', constant_values=0)
print(z)


# pad(array, pad_width, mode, **kwargs)
# array——表示需要填充的数组；

# pad_width——表示每个轴（axis）边缘需要填充的数值数目。 
# 参数输入方式为：（(before_1, after_1), … (before_N, after_N)），其中(before_1, after_1)表示第1轴两边缘分别填充before_1个和after_1个数值。取值为：{sequence, array_like, int}

# mode——表示填充的方式（取值：str字符串或用户提供的函数）,总共有11种填充模式；


# constant’——表示连续填充相同的值，每个轴可以分别指定填充值，constant_values=（x, y）时前面用x填充，后面用y填充，缺省值填充0

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [16]:
17 # 以下表达式运行结果是什么？
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1


False

In [17]:
print (0 * np.nan)

nan


In [18]:
print(np.nan == np.nan)

False


In [19]:
print(np.inf > np.nan)

False


In [20]:
print(np.nan - np.nan)

nan


In [21]:
print(0.3 == 3 * 0.1)

False


In [22]:
18 # 创建一个5X5的矩阵，并设置值1， 2， 3， 4落在其对角线下方位置
z = np.diag(1 + np.arange(4), k=-1)
print(z)

# numpy.diag(v, k=0)[source]
# Extract a diagonal or construct a diagonal array.

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [23]:
19 # 创建一个8X8的矩阵，并且设置成棋盘样式
z = np.zeros((8, 8))
z[1::2, ::2] = 1
z[::2, 1::2] = 1
print(z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [24]:
20 # 考虑一个（6， 7， 8）形状的数组，其第100个元素的索引（x, y, z）是什么？
print(np.unravel_index(100, (6, 7, 8)))
# 将A进行flatten成一维数组之后的索引值

(1, 5, 4)


In [25]:
21 # 用tile函数去创建一个8X8的棋盘样式矩阵
Z = np.tile(np.array([[0,1], [1,0]]), (4,4))
print(Z)

# numpy.tile(A, reps)[source]¶
# Construct an array by repeating A the number of times given by reps.

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [26]:
22 # 对一个5X5的随机矩阵做归一化
z = np.random.random((5,5))
zmin, zmax = z.min(), z.max()
z = (z - zmin) / (zmax - zmin)
print(z)

[[0.31522981 0.52363534 0.23148466 0.87604269 0.86093345]
 [0.16826782 0.19328398 0.         0.45949482 0.74381936]
 [0.59011306 1.         0.16685099 0.60578745 0.52012771]
 [0.23909475 0.24321416 0.9487564  0.71264937 0.7498656 ]
 [0.38697744 0.79221769 0.42630322 0.14759031 0.01149274]]


In [27]:
23 # 创建一个将颜色描述为（RGBA）四个无符号字节的自定义dtype、
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [28]:
24 # 一个5X3的矩阵与一个3X2的矩阵相乘，实矩阵乘积是什么？
z = np.dot(np.ones((5, 3)), np.ones((3,2)))
print(z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [29]:
25 # 给定一个一位数组， 对其在3到8之间的所有数取反
z = np.arange(10)
z[(z > 3) & (z <= 8)] *= -1
print(z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9]


##### 不知道为什么是这样的结果

In [33]:
26 # 下面脚本运行结果是什么？
print(sum(range(5),-1))

10


In [34]:
from numpy import *
print(sum(range(5),-1))

10


In [35]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [38]:
27 # 考虑一个整数向量Z，下列表达合法的是哪个？
'''
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
'''

'\nZ**Z\n2 << Z >> 2\nZ <- Z\n1j*Z\nZ/1/1\nZ<Z>Z\n'

In [39]:
z = np.arange(10)


In [40]:
z ** z

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489])

In [42]:
2 << z >> 2

array([  0,   1,   2,   4,   8,  16,  32,  64, 128, 256])

In [43]:
z >> 2

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2])

In [44]:
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
z < -z

array([False, False, False, False, False, False, False, False, False,
       False])

In [46]:
1j * z

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j, 0.+5.j, 0.+6.j, 0.+7.j,
       0.+8.j, 0.+9.j])

In [47]:
z/1/1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [50]:
z < z

array([False, False, False, False, False, False, False, False, False,
       False])

In [51]:
28 # 下列表达式的结果分别是什么？
'''
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
'''

'\nnp.array(0) / np.array(0)\nnp.array(0) // np.array(0)\nnp.array([np.nan]).astype(int).astype(float)\n'

In [52]:
np.array(0) / np.array(0)

/home/ubuntu/anaconda3/envs/tf/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [53]:
np.array(0) // np.array(0)

/home/ubuntu/anaconda3/envs/tf/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [54]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

In [57]:
29 # 如何对零位浮点数组做舍入？
z = np.random.uniform(-10, +10, 10)
# numpy.random.uniform(low,high,size)
# 功能：从一个均匀分布[low,high)中随机采样，注意定义域是左闭右开，即包含low，不包含high.
print(z)

print(np.copysign(np.ceil(np.abs(z)), z))

# np.copysign:Change the sign of x1 to that of x2, element-wise.
# np.ceil The ceil of the scalar x is the smallest integer i, such that i >= x. It is often denoted 
# 

[ 0.19816043 -4.54393222 -1.13461428  8.07041927  3.21124229 -5.10255554
  2.57934165  3.69237203 -0.96448867  4.15155529]
[ 1. -5. -2.  9.  4. -6.  3.  4. -1.  5.]


In [61]:
30 # 如何找到两个数组中的共同元素？
z1 = np.random.randint(0, 10, 10)
z2 = np.random.randint(0, 10, 10)
# numpy.random.randint(low, high=None, size=None, dtype='l')¶
# Return random integers from low (inclusive) to high (exclusive).

print(np.intersect1d(z1, z2))

# numpy.intersect1d(ar1, ar2, assume_unique=False, return_indices=False)[source]
# Find the intersection of two arrays.


[0 1 4 6 7 8]


In [64]:
31 # 如何忽略所有的numpy警告？
defaults = np.seterr(all="ignore")
z = np.ones(1) / 0

# back to sanity
 # _ = np.seterr(**defaults)

In [68]:
32 # 下面的表达式是正确的吗？
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

nan
1j


In [69]:
33 # 如何得到昨天，今天，明天的日期？

yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

In [71]:
34 # 如何得到所有与2016年7月对于的日期？
z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [72]:
35 # 如何直接在位计算 （A + B) \* (-A/2)(不建立副本)？
A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

# out=None 
# A location into which the result is stored. If provided, it must have a shape that the inputs broadcast to. If not provided or None, a freshly-allocated array is returned. A tuple (possible only as a keyword argument) must have length equal to the number of outputs

array([-1.5, -1.5, -1.5])

In [75]:
36 # 用五种不同的方法去提取一个随机数组的整数部分
z = np.random.uniform(0, 10, 10)    # 在0～10范围里的均匀分布中，随机取10个数，
print(z - z % 1)

[3. 0. 0. 2. 7. 5. 7. 6. 7. 5.]


In [76]:
print(np.floor(z))

[3. 0. 0. 2. 7. 5. 7. 6. 7. 5.]


In [79]:
print(np.ceil(z) - 1)

[3. 0. 0. 2. 7. 5. 7. 6. 7. 5.]


In [80]:
print(z.astype(int))

[3 0 0 2 7 5 7 6 7 5]


In [81]:
print(np.trunc(z))  # np.trunc()   Return the truncated value of the input, element-wise.

[3. 0. 0. 2. 7. 5. 7. 6. 7. 5.]


In [83]:
37 # 创建一个5X5的矩阵，其中每行的数值范围从0到4
z = np.zeros((5,5))
z += np.arange(5)    # broadcast 
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [85]:
38 # 通过考虑一个可生成10个整数的函数，来构建一个数组
def generate():
    for x in range(10):
        yield x
z = np.fromiter(generate(), dtype=float, count=-1)
print(z)

# numpy.fromiter(iterable, dtype, count=-1)
# Create a new 1-dimensional array from an iterable object.

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [87]:
40 # 创建一个长度为10的随机变量，并将其排序
z = np.random.random(10)
z.sort()
print(z)

[0.11969599 0.21497669 0.2751962  0.32298617 0.37680206 0.40052579
 0.42823829 0.64595644 0.95960884 0.98938513]


In [89]:
41 # 对于一个小数组，如何用比 np.sum更快的方式对其求和？
z = np.arange(10)
print(np.add.reduce(z))

# https://codeday.me/bug/20180821/225822.html     np.sum和np.add.reduce有什么区别。

# Reduces a’s dimension by one, by applying ufunc along one axis.

45


In [91]:
42 # 对于两个随机数组A和B，检查他们是否相等
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)    # Returns True if two arrays are element-wise equal within a tolerance.
print(equal)

False


In [94]:
# 方法2
# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False


In [96]:
43 # 创建一个只读数组
z = np.zeros(10)
z.flags.writeable = False
z[0] = 1

ValueError: assignment destination is read-only

In [97]:
44 # 将笛卡尔坐标下的一个10X2的矩阵转化为极坐标形式
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)

[0.64219271 0.93419229 0.83455676 1.01925713 0.76927034 0.62546273
 0.54004377 0.55059695 0.63823566 0.24422102]
[1.53868546 0.26458969 1.0903462  0.95543486 1.53372869 1.4624893
 1.11440388 0.8607541  0.3400975  0.77217808]


In [98]:
45 # 创建一个长度为10的向量，并将向量中最大值替换为1
z = np.random.random(10)
z[z.argmax()] = 1
print(z)

[0.574924   0.80780891 1.         0.76782381 0.09150797 0.60295132
 0.07018211 0.2896295  0.7745761  0.21134108]


In [110]:
46 # 创建一个结构化数组，并实现x 和y坐标覆盖[0, 1]x[0.1]区域
z = np.zeros((5,5), [('x', float), ('y', float)])
# z['x'], z['y'] = np.meshgrid(np.linspace(0, 1, 5),
#                             np.linspace(0, 1, 5))  
# Return coordinate matrices from coordinate vectors.

print(z)
q = np.zeros((4,4), [('r', float), ('t',int), ('b', str)])
print(q)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]
[[(0., 0, '') (0., 0, '') (0., 0, '') (0., 0, '')]
 [(0., 0, '') (0., 0, '') (0., 0, '') (0., 0, '')]
 [(0., 0, '') (0., 0, '') (0., 0, '') (0., 0, '')]
 [(0., 0, '') (0., 0, '') (0., 0, '') (0., 0, '')]]


In [114]:
47 # 给定两个数组X和Y， 构造Cauchy矩阵C （Cij = 1 / (xi - yj)  构造柯西矩阵

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
# ufunc.outer(A, B, **kwargs)   Apply the ufunc op to all pairs (a, b) with a in A and b in B.


print(np.linalg.det(C))
# numpy.linalg.det(a)   Compute the determinant of an array.

3638.1636371179666


In [115]:
48 # 打印每个numpy标量类型的最小值和最大值

for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [123]:
49 # 如何打印一个数组中的所有值
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print (Z)

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

In [119]:
50 # 给定标量时，如何找到数组中最接近标量的值？
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print (Z[index])

4
